### PR TITLE
Cf nginx letsencrypt

### PR DESCRIPTION
**Pull request by joeywas**
This is a working solution of using nginx for reverse proxy/load balancing, Lets Encrypt certificate, and ColdFusion app server.

### CODE REVIEW

**Comment by joeywas** [comment]
Sorry about this Mr Carehart! I thought i was merging into my own fork of awesome-cf-compose

**Comment by carehart** [comment]
Oh, no worries. Am I right to assume you WOULD want to have me pull it into the repo? I saw it just before going to bed and was going to test it today. It does seem it would be a very useful example to add. And please call me Charlie. :-) /CharlieSent from my mobile device. Please pardon typos. 
-------- Original message --------From: Joseph ***@***.***> Date: 11/18/22  10:47 PM  (GMT-06:00) To: carehart/awesome-cf-compose ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [carehart/awesome-cf-compose] Cf nginx letsencrypt (PR #3) 
Sorry about this Mr Carehart! I thought i was merging into my own fork of awesome-cf-compose

**Comment by joeywas** [comment]
> 
Hello Charlie, I am Joseph.

Eventually, I WOULD like to pull it into your repo, but I don't feel it's fleshed out appropriately yet. I need to update some of the configs and make the readme.md more clear. I'm going to close this pull request and clean things up a bit before creating a new one. :)

**Comment by carehart** [comment]
Ok, sir. :-) That said, I have myself skipped on the readme, as it's indeed more work sometimes than creating the other files. :-) Since some are rather self-explanatory, I've figured "better to get the demos in, even without the readme, to benefit those who can use it without the readme". Of course, I do PLAN to finish the readme's that are missing. :-)

**Pull request closed without merging**
